@startuml gps


skinparam actorStyle awesome
actor user as programmer

package Public {
    usecase "gps_api"    as module_public1
    usecase "gps_config" as module_public2

note left of (module_public1)
    Functions publics:
    - gps_register: Register new task
    - gps_unregister: Un register a task
    - gps_start: Start task gps
    - gps_stop: Stop task gps
end note
note left of (module_public2)
    Configure the module
end note
}

package Private {
    usecase "gps_conductor" as module_private1
    usecase "gps_driver"    as module_private2

note left of (module_private1)
    Thread every 100 ms
end note
note left of (module_private2)
    Logic and save dates
end note
}

programmer      --> module_public1
programmer      --> module_public2
module_public2  --> Private
module_public1  --> module_private1
module_public1  --> module_private2
module_private1 --> module_private2

@enduml

