@startuml sevcon


skinparam actorStyle awesome
actor user as programmer

package Public {
    usecase "sevcon_api"    as module_public1
    usecase "sevcon_config" as module_public2

note left of (module_public1)
    Functions publics:
    - sevcon_register: Register new task
    - sevcon_unregister: Un register a task
    - sevcon_start: Start task sevcon
    - sevcon_stop: Stop task sevcon
end note
note left of (module_public2)
    Configure the module
end note
}

package Private {
    usecase "sevcon_conductor" as module_private1
    usecase "sevcon_driver"    as module_private2

note left of (module_private1)
    Thread every 100 ms
end note
note left of (module_private2)
    Logic and save dates
end note
}

programmer      --> module_public1
programmer      --> module_public2
module_public2  --> Private
module_public1  --> module_private1
module_public1  --> module_private2
module_private1 --> module_private2

@enduml

